# Generated by Django 4.2.1 on 2024-02-23 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('delivery_address', models.CharField(max_length=250, verbose_name='Адрес доставки')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('password', models.CharField(max_length=25, verbose_name='Пароль')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dish', models.CharField(max_length=50, verbose_name='Наименование блюда')),
                ('composition_dish', models.TextField(max_length=500, verbose_name='Код блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, default='Добавить изображение', upload_to='')),
            ],
            options={
                'ordering': ['name_dish'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Сумма заказа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('payment_method', models.CharField(choices=[('card', 'Карта'), ('cash', 'Наличные')], max_length=50, verbose_name='Способ оплаты')),
                ('status_cook', models.CharField(choices=[('Готовится', 'Готовится'), ('Приготовлен', 'Приготовлен')], default='Готовится', max_length=32, verbose_name='Статус готовности заказа')),
                ('status_delivery', models.CharField(choices=[('Доставляется', 'Доставляется'), ('Доставлено', 'Доставлено')], default='Доставляется', max_length=32, verbose_name='Статус доставки блюда')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.customer', verbose_name='Код клиента')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Сумма')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Скидка')),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.menu', verbose_name='Код блюда')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
